name: Go build and test
env:
  GO111MODULE: "on"
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  nix-build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'
      
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Build
      run: |
        cd src
        go build -o . -v ./...
        pwd
        ./jacobin -h

    - name: Test
      run: |
        export JACOBIN_TOP=`pwd`
        export JACOBIN_TESTDATA=$JACOBIN_TOP/testdata
        cd src
        export JACOBIN_EXE=`pwd`/jacobin 
        go test -v ./...

    - name: Codecov
      uses: codecov/codecov-action@v3

  windows-build-and-test:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'
      
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Build
      run: |
        cd src
        go build -o . -v ./...
        echo %CD%
        dir
        ./jacobin -h

    - name: Test
      run: |
        $Env:JACOBIN_TOP = $PWD
        $Env:JACOBIN_TOP
        $Env:JACOBIN_TESTDATA = $Env:JACOBIN_TOP
        $Env:JACOBIN_TESTDATA += '\testdata'
        $Env:JACOBIN_TESTDATA
        cd src
        $Env:JACOBIN_EXE = $Env:JACOBIN_TOP
        $Env:JACOBIN_EXE += '\src\jacobin.exe'
        $Env:JACOBIN_EXE
        go test -v ./...

    - name: Codecov
      uses: codecov/codecov-action@v3
